name: Template Synchronization

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # This is needed to ensure the action to push workflow updates in `.github/workflows/*.yml` files.
          # See https://github.com/AndreasAugustin/actions-template-sync#troubleshooting for more details.
          token: '${{ secrets.TEMPLATE_SYNC_PAT }}'
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@0fa0fe63d066890c68f92dd53eed9ca9e38487d1 # v2
        with:
          source_repo_path: position-pal/scala-template
          is_force_push_pr: true
          pr_title: 'chore: upstream template synchronization'
